.PHONY: build clean

build:
	mvn package

clean:
	mvn clean

install:
	mvn install

compile:
	mvn compile

run:
	mvn exec:java -Dexec.mainClass="jmsproject/src/main/java/com/jmsproject/Delegaciones.java"
